### ISSUE TITLE
I'm getting "[bad packet] on bus 0..."

### ISSUE THREAD

**Issue by nick-s-b** [aguinet/usbtop#11]
Hi,
I just installed usbtop and after using modprobe to load usbmon, I gave it a try.

While it does display some info, I'm getting tons of errors of this type... especially when I move my mouse around:

````
[bad packet] on bus 0, captured a packet claimed to be on bus 2.
...
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
````

I did some searching but cannot figure out what's wrong.   I'm using Arch and my libs are:
````
libusb: 1.0.21-2
libpcap: 1.8.1-2
````
I do have a USB3 hub and all my devices seem to work fine.

````
Bus 004 Device 002: ID 05f3:0612 Genesys Logic, Inc. Hub
Bus 004 Device 001: ID 1f6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 046a:b539 Logitech, Inc. 
Bus 003 Device 002: ID 05f3:0610 Genesys Logic, Inc. 4-port hub
````
I know this might not even be a usbtop specific issue but I don't know where to even begin searching for 
 an answer as to what's wrong. Anyone know what's up? Thanks.

**Comment by slokhorst** [comment]
Did you install `usbtop` or `usbtop-git`? This looks like #7 which is fixed in `usbtop-git`.

**Comment by nick-s-b** [comment]
@slokhorst thank you!!! Just installed usbtop-git and I don't see any errors.

**Comment by slokhorst** [comment]
@aguinet maybe time for a new release? So the fix will propagate to the downstream packages.

**Comment by aguinet** [comment]
Done here https://github.com/aguinet/usbtop/releases/tag/release-0.2 !
