### ISSUE TITLE
More thorough install instructions.

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [aguinet/usbtop#20]
FYI, here's some more thorough install instructions I just wrote in case you want to use them in your install instructions here. https://unix.stackexchange.com/questions/10671/usb-performance-traffic-monitor/489268#489268

**Comment by aguinet** [comment]
Hello! Thanks for the instructions!

Debian and ubuntu packages seems to have landed, so that might also be an easier way to install usbtop on these systems. I will add this link to the installation file.
