### ISSUE TITLE
No output when ran without proper permission

### ISSUE THREAD

**Issue by slokhorst** [aguinet/usbtop#3]
When I run `usbtop` as regular user, the following message flashes by:
````
Error while capturing traffic from usbmon1: usbmon1: Can't open USB bus file /sys/kernel/debug/usb/usbmon/1t: Permission denied
````

But it disappears in a fraction of a second, and it is unclear what the problem is. Is there a way to show this error longer, or print a custom error message, hinting what the problem is?

(By the way, this program is exactly what I was looking for! It seems to be the only simple way to read out USB bandwidth.. I'm quite surprised that it isn't well known yet!)

**Comment by aguinet** [comment]
Hello,

I just pushed a commit that makes usbtop exit if it couldn't have successfully open any USB bus.
These error(s) can happen if you don't have loaded the usbmon kernel module (sudo modprobe usbmon) and/or if you don't run this software as root.

As a side note, that's cool if this software helps you :)

**Comment by aguinet** [comment]
Please let me know if this fixes your issues!

**Comment by slokhorst** [comment]
Perfect! Thank you for the quick fix!
