### ISSUE TITLE
Building error on Ubuntu 16.04 Boost not found

### ISSUE THREAD

**Issue by Saentist** [aguinet/usbtop#4]
$aptitude install libboost-dev libpcap-dev
libboost-dev is already installed at the requested version (1.58.0.1ubuntu1)
libpcap-dev is already installed at the requested version (1.7.4-2)
libboost-dev is already installed at the requested version (1.58.0.1ubuntu1)
libpcap-dev is already installed at the requested version (1.7.4-2)
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

$cmake .
-- Pcap include dirs set to /usr/include
-- Pcap library set to  /usr/lib/i386-linux-gnu/libpcap.so
-- Could NOT find Boost
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/usbtop

**Comment by slokhorst** [comment]
Try installing `libboost-thread-dev` and `libboost-system-dev`.

**Comment by Saentist** [comment]
Yes this helped 10x
README.md need to be updated

**Comment by aguinet** [comment]
I'll update the INSTALL file with these packages. The modprobe command is already in the README!
