### ISSUE TITLE
throughput measured on usb device seems wrong

### ISSUE THREAD

**Issue by jrsphoto** [aguinet/usbtop#6]
I have an RTL-SDR usb sdr receiver, that I've been testing with usbtop to determin how much data its sending over the usb bus.   I can use the command rtl_test -s 2.4e6 to tell it to sample at 2.4MHz bandwidth, which should put around 4800kB/s on the usb bus, but I'm only geting 1160kB/sec.  In fact, if I change the sample rate to 3.4Mhz, which should peg the usb2 interface, It stays at 1160kB/sec.  

I'm on ubuntu 16.04.3 LTS on an i5 processor with 16gb of ram..  Source compiled direct from github and compiled with no errors or warnings.

**Comment by aguinet** [comment]
Hello @jrsphoto !

Thanks for your tests! I was actually not very confident about the algorithm used for computing the bandwidth, and your results seem to confirm that! Do you have any suggestions/improvements on how the bandwidth measurement should be done? (that is, for instance, at which frequency should we compute it, using which sizes, etc...). Thanks!

**Comment by aguinet** [comment]
For information, all bandwidth computation related code is happening here: https://github.com/aguinet/usbtop/blob/master/src/usb_stats.cpp !

**Comment by Nable80** [comment]
11270.87 kB/s ~ 90.167 Mbits/s. Does it resolve your doubts?

**Comment by mangodan2003** [comment]
I would hazard a guess that its coincidence. The units displayed are kb/s - that's kilo bits  per second, and USB throughput is normally measured in bits not bytes, presumably due to being a serial connection.  I'll have a look at usb_stats.cpp and see if its a possibility though.

**Comment by mangodan2003** [comment]
ah ok, not had a chance to look back at this yet but good to know. Thanks.

**Comment by dentys03** [comment]
Hi.

could you please clarify?
The output of usbtop is kb/s, kB/s or kiB/s ?

**Comment by aguinet** [comment]
It's in KiB/s (KiB as in https://en.wikipedia.org/wiki/Kibibyte)

**Comment by dentys03** [comment]
Thank you.
The output includes the usb overhead too?

**Comment by aguinet** [comment]
It does. Closing this issue. Do notbhesitate to re-open if you have any question!
