### ISSUE TITLE
Getting a lot of errors when running usbmon

### ISSUE THREAD

**Issue by oxoocoffee** [aguinet/usbtop#7]
I am getting lots of there errors when running after loading kernel module and starting program 
sudo usbmon

[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.
[bad packet] on bus 0, captured a packet claimed to be on bus 3.

**Comment by g0tar** [comment]
Explained and solved in #8.

**Comment by aguinet** [comment]
Just being merged!
